#!/bin/bash

#menü zur auswahl der funktionen mit zahleneingabe

echo "EventAufgabenPlaner - Menu"
echo "1 - Start Development Local"
echo "2 - Start AWS Public IP"
echo "3 - Update AWS Public IP from the Rpository"
echo "4 - Backup Database from AWS"
echo "5 - Restore Database to AWS"
echo "0 - Exit"

read -p "Enter your choice: " choice

case $choice in
1)
    echo "Start Development Local"
    ./start-dev.sh
    ;;
2)
    echo "Deploy on AWS Public IP"
    ./deployment.sh
    ;;
3)
    echo "Update on AWS Public IP from the Rpository"
    ./update.sh
    ;;
4)
    echo "Backup Database from AWS"
    ./backup-download.sh
    ;;
5)
    echo "Restore Database to AWS"
    ./backup-upload.sh
    ;;
0)
    echo "Exit"
    exit 0
    ;;
*)
    echo "Invalid choice"
    ;;
esac
